---
# tasks file for addldap

- name: Show ldap variables
  debug:
    var: ldap

- name: register whether the config folder is already present
  stat:
    path: "{{docker_export_location}}/galaxy-central/config"
  register: config_folder
  
- name: Show config folder presence
  debug:
    var: config_folder
 

- name: create default galaxy folders
  docker_container:
    volumes: "{{docker_export_location}}:/export/"
    image: "{{docker_image}}"
    name: "{{docker_container_name}}"
    state: started
    command: "python /usr/local/bin/export_user_files.py $PG_DATA_DIR_DEFAULT"
  when: not True # {{galaxy_config_folder_present}} 


- name: Create auth_conf.xml file in config folder
  template: 
    dest: "{{docker_export_location}}/galaxy-central/config/auth_conf.xml"
    force: yes
    src: auth_conf.xml.j2
    trim_blocks: True #Ansible 2.3 required
