---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

# A list of tasks that sets up the backup user to rsync the backups to a remote host

- name: create rsync script
  template:
    src: "rsyncscript.sh.j2"
    dest: "{{galaxy_docker_backup_location}}/scripts/rsyncscript.sh"
    mode: 0700
  vars:
    src: "{{galaxy_docker_backup_location}}"
    host_address: "{{item.host}}"
    dest: "{{item.dest}}"
    user: "{{item.user |default('')}}"
    compression_level: "{{item.compression_level}}"
    delete: "{{item.delete}}"
  with_items:
    - "{{backup_galaxy_rsync_settings}}"

- name: generate_ssh_key
  user:
    name: "{{galaxy_docker_docker_user}}"
    generate_ssh_key: yes

- name: copy public key of backup user to ansible host
  fetch:
    dest: "{{ssh_dir}}/{{galaxy_docker_docker_user}}_public-key/id_rsa.pub"
    flat: yes
    src: "/home/{{galaxy_docker_docker_user}}/{{backup_ssh_key_file}}.pub"
    validate_checksum: yes

- name: Add remote backup server to the known_hosts file
  known_hosts:
    name: "{{backup_galaxy_rsync_settings.host}}"
    state: present
    key: "{{backup_galaxy_rsync_settings.host}} {{backup_galaxy_rsync_settings.host_public_key}}"
#    hash_host: True

- name: Hash known_hosts file.
  command: "ssh-keygen -Hf {{known_hosts}}"
  vars:
    known_hosts: "~/.ssh/known_hosts"

- name: Set job in cron to rsync backups to a remote location
  cron:
    job: "bash {{galaxy_docker_backup_location}}/scripts/rsyncscript.sh >> {{galaxy_docker_backup_location}}/logs/rsync.log 2>&1"
    state: present
    user: "{{galaxy_docker_docker_user}}"
    backup: yes
    name: "Rsync to the backup host"
    month: "{{item.cron.month | default(omit) }}"
    day: "{{item.cron.day | default(omit) }}"
    weekday: "{{item.cron.weekday | default(omit)}}"
    hour: "{{item.cron.hour | default(omit)}}"
    minute: "{{item.cron.minute | default(omit)}}"
    special_time: "{{item.cron.special_time | default(omit)}}"
  with_items:
    - "{{backup_galaxy_rsync_settings}}"
