- name: Install required bioblend package
  pip:
    name: "{{ bioblend_packages }}"
    state: latest

- name: Create tool list directory on the server
  file:
    path: "{{work_dir}}"
    state: directory

- name: Check whether working directory is empty
  find:
    paths: "{{work_dir}}"
    patterns:
      - "*"
  register: work_dir_files

- name: show work_dir_files
  debug:
    msg: "{{work_dir_files.matched}}"
    verbosity: 1

- name: Fail if directory is not empty
  fail:
    msg: "Directory already contains files with .yml or .yaml extension or contains an old shed_install.py. Please remove these files or specify another directory. {{work_dir_files.files}}"
  when: '"{{work_dir_files.matched}}" > "0"'

- name: Move tool directory on galaxy server
  copy:
    dest: "{{work_dir}}"
    src: "{{tool_list_dir}}"
    force: yes

- name: Create a file list from the directory
  find: 
    paths: "{{work_dir}}"
    patterns: 
      - "*.yml"
      - "*.yaml"
  register: tools

- name: Set list of tool list files as a fact
  set_fact:
    tool_list_files: "{{tools|json_query('files[*].path')}}"

- name: delete api key from tool list files
  lineinfile:
    destfile: "{{item}}"
    regexp: "api_key:.*"
    state: absent
#    line: "api_key{{':'}} {{galaxy_master_api_key}}"
  with_items: "{{tool_list_files}}"

- name: Show tool_list_files
  debug:
    var: tool_list_files
    verbosity: 1

- name: delete galaxy_instance from tool list files
  lineinfile:
    destfile: "{{item}}"
    regexp: "galaxy_instance:.*"
    state: absent     
#    line: "galaxy_instance{{':'}} 127.0.0.1"
  with_items: "{{tool_list_files}}"

- name: copy ephemeris tool installer to server
  copy:
    src: shed_install.py
    dest: "{{work_dir}}/shed_install.py"

- name: Use ephemeris shed install to install tools 
  command: "python {{work_dir}}/shed_install.py -g localhost:{{galaxy_web_port}} -a {{galaxy_master_api_key}} -t {{item}}"
  with_items: "{{tool_list_files}}"
  ignore_errors: yes

- name: remove added files
  file:
    path: "{{work_dir}}"
    state: absent
