language: python
sudo: false
matrix:
  include:
    - python: 2.7
# Submodules required for integration testing with vagrant only, which is not supported by travis.
git:
  submodules: false
install:
  - pip install mkdocs yamllint
script:
  - bash test/yamllinting.sh
  - bash test/mkdocs.sh

# Keep inboxes nice and clean.
notifications:
  email: false
