language: python
sudo: false
matrix:
  include:
    - python: 2.7
# Submodules required for integration testing with vagrant only, which is not supported by travis.
git:
  submodules: false
install:
  - pip install mkdocs yamllint
script:
  - yamllint -c .yamllint.yml $(git ls-files | grep  -e ".*.ya?ml")
  - yamllint -c .yamllint.yml $(git ls-files | grep  -e ".*.settings")
  - mkdocs build --clean
