language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env:
        TESTCOMMAND: yamllint -c .yamllint.yml $(git ls-files | grep  -e ".*.ya?ml") $(git ls-files | grep  -e ".*.settings")
    - python: 2.7
      env:
        TESTCOMMAND: mkdocs build --clean
  install:
    - apt install git
    - pip install mkdocs yamllint
  script:
    - $TESTCOMMAND
# Submodules required for integration testing with vagrant only
git:
  submodules: false
