language: python
sudo: false
services:
  - docker
matrix:
  include:
    - python: 2.7
      env:
        TOX_ENV: py27-lint
    #- python: 2.7
    #  env:
    #    TOX_ENV: playbook
    #    test_hostname: centos-7
    #    privileged: True
    #- python: 2.7
    #  env:
    #    TOX_ENV: playbook
    #    test_hostname: centos-7
    #    privileged: False
    - python: 2.7
      env:
        TOX_ENV: playbook
        test_hostname: ubuntu-16.04
        privileged: True
    - python: 2.7
      env:
        TOX_ENV: playbook
        test_hostname: ubuntu-16.04
        privileged: False
# Submodules required for integration testing with vagrant only, which is not supported by travis.
git:
  submodules: false

install:
  - pip install tox
  - apt install source

script:
  - tox -e $TOX_ENV

# Keep inboxes nice and clean.
notifications:
  email: false
