--- # Deletes a galaxy instance based on the galaxydocker.config file 

- hosts: "{{var_hosts}}"
  become: yes
  become_method: sudo
  gather_facts: yes
  vars_files:
  - config/galaxydocker.config
  vars:
    - delete_files: True
  roles:
  - deletegalaxy
