--- # Installs latest docker version from repository on a remote machine 

- hosts: testgalaxy
  become: yes
  user: ruben
  connection: ssh
  gather_facts: yes
  vars_files:
    - config/hosts.config
    - config/galaxydocker.config
  roles:
    - installdocker
     
