--- # Set up a remote machine with docker, pulls the galaxy docker image and installs tools using the API key. 

- hosts: "{{var_hosts}}"
  become: yes
  become_method: sudo
  gather_facts: yes
  vars_files:
  - config/galaxydocker.config
  vars:
  roles:
    - installdocker
    - galaxyfirewall
    - rundockergalaxy     
    - installtools
