--- # Playbook that contains all roles. 

- hosts: "{{ hosts }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  pre_tasks:
  - include_vars:
      file: "run/{{item}}"
    with_items:
      - "{{run | default('[]')}}"    
  roles:
    - { role: installdocker, when: "{{ installdocker | default('False')}}" }
    - { role: galaxyfirewall, when: "{{ galaxyfirewall | default('False')}}" }
    - { role: migrate, when: "{{ migrate | default('False')}}" }
    - { role: rundockergalaxy, when: "{{ rundockergalaxy | default('False')}}" }    
    - { role: installtools, when: "{{ installtools | default('False')}}" }
    - { role: backupgalaxy, when: "{{ backupgalaxy | default('False')}}" }
    - { role: deletegalaxy, when: "{{ deletegalaxy | default('False')}}" }
