- name: Create config folder
  docker_container:
    volumes: "{{docker_export_location}}:/export/"
    image: "{{docker_image}}"
    name: "export_folder_creator_{{ansible_date_time.epoch}}"
    state: started
    user: "{{galaxy_docker_web_user_id}}"
    command: "python /usr/local/bin/export_user_files.py $PG_DATA_DIR_DEFAULT"
