---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

- meta: flush_handlers

- name: Install required ephemeris package
  pip:
    name: "{{ ephemeris_package.name }}"
    state: latest

- name: Make sure work directories are empty
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{galaxy_docker_tool_dir}}"
    - "{{galaxy_docker_dbkeys_dir}}"

- name: Make sure work directories are created
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{galaxy_docker_tool_dir}}"
    - "{{galaxy_docker_dbkeys_dir}}"

- name: Find yml files in tool list directory
  find:
    paths: "{{tool_list_dir}}"
    patterns:
      - "*.yml"
      - "*.yaml"
  register: "{{item.register}}"
  delegate_to: 127.0.0.1
  become: no
  with_items:
    - path: "{{tool_list_dir}}"
      register: tools
    - path: "{{dbkeys_list_dir}}"
      register: dbkeys

- name: Show which yamls will be transferred
  debug: 
    var: "{{item}}"
    verbosity: 0
  with_items:
    - tools
    - dbkeys

- name: delete api key from files
  lineinfile:
    destfile: "{{item.path}}"
    regexp: "api_key:.*"
    state: absent
  with_items: 
    - "{{tools.files}}"
    - "{{dbkeys.files}}"
  become: no
  delegate_to: 127.0.0.1

- name: delete galaxy_instance from files
  lineinfile:
    destfile: "{{item.path}}"
    regexp: "galaxy_instance:.*"
    state: absent     
  with_items: 
    - "{{tools.files}}"
    - "{{dbkeys.files}}"
  become: no
  delegate_to: 127.0.0.1

- name: Move tools to galaxy server
  copy:
    dest: "{{galaxy_docker_tool_dir}}/{{item.path | basename}}"
    src: "{{item.path}}"
    force: yes
    mode: 0600
  with_items:
    - "{{tools.files}}"

- name: Move dbkeys to galaxy server
  copy:
    dest: "{{galaxy_docker_dbkeys_dir}}/{{item.path | basename}}"
    src: "{{item.path}}"
    force: yes
    mode: 0600
  with_items:
    - "{{dbkeys.files}}"

- name: Create a file list from the directory
  find: 
    paths: "{{item.path}}"
    patterns: 
      - "*.yml"
      - "*.yaml"
  register: "{{item.register}}"
  with_items:
    - path: "{{galaxy_docker_tool_dir}}"
      register: tools
    - path: "{{galaxy_docker_dbkeys_dir}}"
      register: dbkeys

- name: Use ephemeris shed install to install tools 
  command: "shed-install -g localhost:{{galaxy_web_port}} -a {{galaxy_master_api_key}} -t {{item.path}}"
  with_items: "{{tools.files}}"
  ignore_errors: yes

- name: Use ephemeris shed install to install reference genomes
  command: "shed-install -g localhost:{{galaxy_web_port}} -a {{galaxy_master_api_key}} -d {{item.path}}"
  with_items: "{{dbkeys.files}}"
  ignore_errors: yes


- name: remove added files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{galaxy_docker_tool_dir}}"
    - "{{galaxy_docker_dbkeys_dir}}"
