---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

- meta: flush_handlers

- name: Install required ephemeris package
  pip:
    name: "{{ ephemeris_package }}"
    state: latest

- name: Create empty temp directory
  file:
    path: "{{galaxy_docker_tmp_dir}}"
    state: "{{item}}"
    mode: 0700
  with_items:
    - absent
    - directory

- name: Find yml files in tool and dbkeys directory
  find:
    paths: "{{item}}"
    patterns:
      - "*.yml"
      - "*.yaml"
  register: yamls
  delegate_to: 127.0.0.1
  become: no
  with_items:
    - "{{tool_list_dir}}"
    - "{{dbkeys_list_dir}}"

- set_fact:
    tools: "{{yamls.results[0]}}"
    dbkeys: "{{yamls.results[1]}}"

- name: Show which yamls will be transferred
  debug: 
    var: "{{item}}"
    verbosity: 1
  with_items:
    - tools
    - dbkeys

- name: delete api key from files
  lineinfile:
    destfile: "{{item.path}}"
    regexp: "api_key:.*"
    state: absent
  with_items: 
    - "{{tools.files}}"
    - "{{dbkeys.files}}"
  become: no
  delegate_to: 127.0.0.1

- name: delete galaxy_instance from files
  lineinfile:
    destfile: "{{item.path}}"
    regexp: "galaxy_instance:.*"
    state: absent     
  with_items: 
    - "{{tools.files}}"
    - "{{dbkeys.files}}"
  become: no
  delegate_to: 127.0.0.1

- name: Move tools and dbkeys to server
  copy:
    dest: "{{galaxy_docker_tmp_dir}}/tools.{{item.path | basename}}"
    src: "{{item.path}}"
    force: yes
    mode: 0600
  with_items:
    - "{{tools.files}}"

- name: Move dbkeys to galaxy server
  copy:
    dest: "{{galaxy_docker_tmp_dir}}/dbkeys.{{item.path | basename}}"
    src: "{{item.path}}"
    force: yes
    mode: 0600
  with_items:
    - "{{dbkeys.files}}"

- name: Use ephemeris shed install to install tools 
  command: "shed-install -g localhost:{{galaxy_web_port}} -a {{galaxy_master_api_key}} -t {{galaxy_docker_tmp_dir}}/tools.{{item.path | basename}}"
  with_items: "{{tools.files}}"
  ignore_errors: yes

- name: Use ephemeris shed install to install reference genomes
  command: "shed-install -g localhost:{{galaxy_web_port}} -a {{galaxy_master_api_key}} -d {{galaxy_docker_tmp_dir}}/dbkeys.{{item.path | basename}}"
  with_items: "{{dbkeys.files}}"
  ignore_errors: yes

- name: remove added files
  file:
    path: "{{galaxy_docker_tmp_dir}}"
    state: absent
