---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

test: False
overwrite_config_files: False #Overwrites old config files with new distribution_config files

no_overwrite: "-n" # No overwrite parameter for cp shell command.

##
#Files to be migrated for testing
##

#root folder is the export folder
# dest: "" therefore equals copying directly into the root folder.
migrated_files:
  - src: "galaxy-central/config"
    dest: "galaxy-central"
  - src: "postgresql"
    dest: ""

##
#Files to be copied from .distribution_config to new config
##
new_config_files:
  - src: ".distribution_config/."
    dest: "galaxy-central/config"
