- name: Create key directory
  file:
    path: "{{galaxy_docker_remote_key_dir}}"
    state: directory
    mode: 0600

- name: Create ssh keys
  command: "ssh-keygen -t rsa -f {{galaxy_docker_remote_key_dir}}/{{item}}"
  args:
    creates: "{{galaxy_docker_remote_key_dir}}/{{item}}"
  with_items:
    - "{{galaxy_docker_docker_user}}"
    - "{{galaxy_docker_web_user}}"
    - "{{galaxy_docker_database_user}}"

# Weird ansible limtitation initiated shannanigans
- name: Get docker user public key
  command: cat {{galaxy_docker_remote_key_dir}}/{{galaxy_docker_docker_user}}.pub
  register: galaxy_docker_docker_user_public_key

- name: Get web user public key
  command: cat {{galaxy_docker_remote_key_dir}}/{{galaxy_docker_web_user}}.pub
  register: galaxy_docker_web_user_public_key

- name: Get database user public key
  command: cat {{galaxy_docker_remote_key_dir}}/{{galaxy_docker_database_user}}.pub
  register: galaxy_docker_database_user_public_key

- name: Add keys to authorized key files
  authorized_key:
    key: "{{galaxy_docker_docker_user_public_key.stdout}}"
    user: "{{galaxy_docker_docker_user}}"

- name: Add keys to authorized key files
  authorized_key:
    key: "{{galaxy_docker_web_user_public_key.stdout}}"
    user: "{{galaxy_docker_web_user}}"

- name: Add keys to authorized key files
  authorized_key:
    key: "{{galaxy_docker_database_user_public_key.stdout}}"
    user: "{{galaxy_docker_database_user}}"


# The proper way! But does not work.
#- name: Add keys to authorized key files
#  authorized_key:
#    key: "file://{{galaxy_docker_remote_key_dir}}/{{item}}.pub"
#    user: "{{item}}"
#  with_items:
#    - "{{galaxy_docker_docker_user}}"
#    - "{{galaxy_docker_web_user}}"
#    - "{{galaxy_docker_database_user}}"

- name: Copy key to ansible host
  synchronize:
    mode: pull
    dest: "{{galaxy_docker_ssh_dir}}/"
    src: "{{galaxy_docker_remote_key_dir}}/{{item}}"
    perms: yes
  vars:
    ansible_ssh_pipelining: False
  with_items:
    - "{{galaxy_docker_docker_user}}"
    - "{{galaxy_docker_web_user}}"
    - "{{galaxy_docker_database_user}}"


- name: Remove key directory
  file:
    path: "{{galaxy_docker_remote_key_dir}}"
    state: absent
