---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

- name: Add systemd unit file.
  template:
    dest: /etc/systemd/system/galaxy.service
    src: galaxy.service.j2
    force: yes

- name: register if a galaxy container exists
  command: "docker ps -aq -f name={{galaxy_docker_container_name}}$"
  register: galaxy_container_exists
  changed_when: false

- name: Start a dummy container
  docker_container:
    name: "{{galaxy_docker_container_name}}"
    image: hello-world
  when:
    - galaxy_container_exists is defined
    - galaxy_container_exists.stdout ==''

- name: Galaxy should be started on reboot.
  systemd:
    enabled: yes
    name: galaxy.service
