---
# -----
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
# .....

- name: Start docker installation
  include_role:
    name: installdocker
  when: installdocker

- import_tasks: install_packages.yml
  when: galaxy_docker_install_packages

- import_tasks: add_users.yml
  when: galaxy_docker_add_users

- import_tasks: add_user_ssh_keys.yml
  when: galaxy_docker_create_user_ssh_keys

- import_tasks: galaxy_startup_service.yml
  when: galaxy_docker_prerequisites_startup_service

- import_tasks: create_export_folder.yml
  when: galaxy_docker_create_export_folder

- import_tasks: nginxsettings.yml
  when: galay_docker_nginx_settings

- name: Start nginx installation
  include_role:
    name: jdauphant.nginx
  when: ansible_role_nginx

- import_tasks: galaxyfirewall.yml
  when: galaxy_docker_firewall
