---
# tasks file for importdb

- name: Register the files that are copied
  find:
    paths: "{{playbook_dir}}/files/{{import_db}}"
    patterns: "*"
  register: dump_file_list
  delegate_to: 127.0.0.1

- name: show dump_file_list
  debug:
    var: dump_file_list

- name: Fail when multiple files are found
  fail: 
    msg: "Multiple files in files/{{import_db}}"
  when: "dump_file_list.matched > 1"

- name: Display when no files are found
  debug:
    msg: "No files in files/{{import_db}}. Skipping importdb role"
  when: "dump_file_list.matched < 1"

- include: import.yml 
  when: "dump_file_list.matched == 1"

