---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

- name: Register whether config folder is already created
  stat:
    path: "{{galaxy_docker_export_location}}/galaxy-central/config"
  register: default_config_folder
  until: default_config_folder.stat.exists
  retries: 10
  delay: 15

- include: template_ldap.yml
  when: galaxy_docker_template_ldap

- include: galaxywelcome.yml
  when: galaxy_docker_template_welcome

- include: setup_cluster_general.yml
  when: galaxy_docker_cluster | bool

- include: setupsge.yml
  when: galaxy_docker_cluster == 'sge'

- include: report_user.yml
