- name: Register whether config folder is already created
  stat:
    path: "{{docker_export_location}}/galaxy-central/config"
  register: default_config_folder
  until: default_config_folder.stat.exists
  retries: 10
  delay: 15

- include: addldap.yml
  when: addldap

- include: galaxy_welcome.yml
  when: galaxywelcome

- include: setup_cluster_general.yml
  when: galaxy_docker_cluster
