- name: Register whether config folder is already created
  stat:
    path: "{{docker_export_location}}/galaxy-central/config"
  register: default_config_folder
  until: default_config_folder.stat.exists
  retries: 10
  delay: 15

- include: addldap.yml
  when: addldap
  
