---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

- fail:
    msg: "galaxy_report_user and galaxy_report_password should be defined!"
  when: (galaxy_report_password is not defined) or (galaxy_report_user is not defined)


- name: Add report_htpasswd file for Report Webapp
  htpasswd:
    create: yes
    crypt_scheme: sha512_crypt #Other secure choices: https://passlib.readthedocs.io/en/stable/narr/quickstart.html#recommended-hashes
    name: "{{galaxy_report_user}}"
    password: "{{galaxy_report_password}}"
    path: "{{docker_export_location}}/reports_htpasswd"
