- name: Create cluster filesystem folders
  file:
      path: "{{item}}"
      state: directory
  with_items:
    - "{{optional_environment_settings.GALAXY_CONFIG_JOB_WORKING_DIRECTORY}}"
    - "{{optional_environment_settings.GALAXY_CONFIG_FILE_PATH}}"
  when:
    - optional_environment_settings.GALAXY_CONFIG_JOB_WORKING_DIRECTORY is defined
    - optional_environment_settings.GALAXY_CONFIG_FILE_PATH is defined

- name: Create cluster filesystem new file path
  file:
    path: "{{optional_environment_settings.GALAXY_CONFIG_NEW_FILE_PATH}}"
    state: directory
    mode: 01777

- name: make sure galaxy_venv directory exists
  file:
    path: "{{galaxy_cluster_virtualenv}}"
    state: directory
  when: galaxy_cluster_virtualenv is defined

- name: Create virtualenv
  pip:
    name: "pip>=8.1"
    virtualenv: "{{galaxy_cluster_virtualenv}}"
  when: galaxy_cluster_virtualenv is defined

- name: Install pinned-requirements
  pip:
    requirements: "{{docker_export_location}}/galaxy-central/lib/galaxy/dependencies/pinned-requirements.txt"
    virtualenv: "{{galaxy_cluster_virtualenv}}"
    extra_args: --index-url https://wheels.galaxyproject.org/simple --only-binary all
  when: galaxy_cluster_virtualenv is defined

- name: Add some conditional-requirements.
  pip:
    name: "{{item}}"
    virtualenv: "{{galaxy_cluster_virtualenv}}"
    extra_args: --index-url https://wheels.galaxyproject.org/simple --only-binary all
  with_items:
    - "psycopg2==2.6.1"
    - "drmaa"
    - "uWSGI"
    - "watchdog"
  when: galaxy_cluster_virtualenv is defined

- name: Create job_conf.xml
  template:
    dest: "{{docker_export_location}}/galaxy-central/config/job_conf.xml"
    src: "job_conf.xml.j2"
    force: yes

- name: Edit shed_tool_conf.xml to contain the right tool shed location
  lineinfile:
    backrefs: yes
    backup: yes
    state: present
    regexp: '(<toolbox tool_path=")(.*)(">)'
    line: '\1{{docker_export_location}}/shed_tools\3'
    path: "{{docker_export_location}}/galaxy-central/config/shed_tool_conf.xml"

- name: Create environment setup file
  template:
    dest: "{{docker_export_location}}/environment_setup_file.sh"
    src: "environment_setup_file.sh.j2"
    force: yes
