- name: register dump_file
  set_fact:
    galaxy_docker_imported_db: "{{dump_file_list.files[0].path | basename }}"

- name: show database name
  debug:
    var: galaxy_docker_imported_db
    verbosity: 1

- name: Create folder to import database into
  file:
    path: "{{galaxy_docker_imported_db_location}}"
    state: directory
    mode: 0700

- name: copy database file using rsync
  synchronize:
    mode: push
    dest: "{{galaxy_docker_imported_db_location}}/{{galaxy_docker_imported_db}}"
    src: "{{galaxy_docker_import_db_location}}/{{galaxy_docker_imported_db}}"
    perms: yes
    compress: yes
  vars:
    ansible_ssh_pipelining: False #otherwise synchronize does not work

- name: Create script to delete old database and create new empty database
  template:
    src: new_empty_db.j2
    dest: "{{galaxy_docker_import_db_location}}/new_empty_db"
    mode: 0600
