---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

# defaults file for galaxy_docker
galaxy_docker_remote_key_dir: /tmp/keys
#users
galaxy_docker_docker_user: galaxy_docker
galaxy_docker_docker_user_private_key: "{{ssh_dir}}/{{galaxy_docker_docker_user}}"
galaxy_docker_docker_user_virtualenv: "{{galaxy_docker_docker_user_home}}/virtualenv"
galaxy_docker_docker_user_home: "/home/{{galaxy_docker_docker_user}}"

galaxy_docker_database_user: postgres
galaxy_docker_database_user_id: 1550
galaxy_docker_database_group_id: 1550
galaxy_docker_database_user_private_key: "{{ssh_dir}}/{{galaxy_docker_database_user}}"
galaxy_docker_database_user_home: "/home/{{galaxy_docker_database_user}}"

galaxy_docker_web_user: galaxy
galaxy_docker_web_user_id: 1450
galaxy_docker_web_group_id: 1450
galaxy_docker_web_user_private_key: "{{ssh_dir}}/{{galaxy_docker_web_user}}"
galaxy_docker_web_user_virtualenv: "{{galaxy_docker_web_user_home}}/virtualenv"
galaxy_docker_web_user_home: "/home/{{galaxy_docker_web_user}}"

galaxy_docker_provision_user: admin@galaxy.org
galaxy_docker_provision_key: admin

# docker defaults
galaxy_docker_docker_user_groups: docker
docker_image: bgruening/galaxy-stable
docker_environment_file_location: "{{galaxy_docker_docker_user_home}}/galaxydocker.env"
docker_export_location: "/data/galaxy/galaxy_storage"
galaxy_docker_export_location_mode: "0755" # If not accessible for all users (--x) then postgres does not work.
docker_container_name: galaxy
docker_provision_container_name: galaxy-provision
docker_container_hostname: galaxy-docker
docker_extra_volumes: ""
docker_build_dir: "{{galaxy_docker_docker_user_home}}/docker_build/"
bgruening_galaxy_stable_version: latest
docker_image_changed_uids: "galaxy_stable_changed_uids:{{bgruening_galaxy_stable_version}}"
# firewall, nginx and ports
ufw_profile: galaxy
galaxy_docker_test_ufw_profile: testgalaxy
public_galaxy_web_port: 80
galaxy_web_port: 8080
galaxy_docker_provision_port: 8008
# Bgruening container defaults
galaxy_docker_container_database_name: galaxy
galaxy_docker_container_database_username: "galaxy"

# File locations:
welcome_dir: "{{playbook_dir}}/files/{{inventory_hostname}}/welcome/"
galaxy_docker_import_db_dir: "{{playbook_dir}}/files/{{inventory_hostname}}/database_import/"
tool_list_dir: "{{playbook_dir}}/files/{{inventory_hostname}}/tools/"
dbkeys_list_dir: "{{playbook_dir}}/files/{{inventory_hostname}}/dbkeys/"
genomes_dir: "{{playbook_dir}}/files/{{inventory_hostname}}/genomes/"
galaxy_docker_extract_database_dir: "files/{{inventory_hostname}}/database_extract/"
docker_custom_image_dir: "files/{{inventory_hostname}}/docker_custom_image/"

ansible_generated_vars_dir: "/tmp/ansible_generated_vars/{{ansible_hostname}}/"
ssh_dir: "{{playbook_dir}}/files/{{ inventory_hostname }}/ssh"

# defaults for addldap
ldap_defaults:
  login_use_username: True
  allow_password_change: False
  allow_register: False
  auto_register: True
  continue_on_failure: False
  email_suffix: ""
#  options: ""

# defaults for cronbackupdb
cronbackupdb_log_timestamp: "TZ='UTC' date +'%Z %F %T >'"
backup_ssh_key_file: ".ssh/id_rsa"
default_rsync_settings:
  delete: True
  compression_level: 0
  cron:
    special_time: "hourly"

backup_rsync_settings: {}
backup_rsync_remote_host: False

# defaults for deletegalaxy
delete_files: False
delete_test_upgrade: False
delete_backup_files: False

# defaults for databases

## Defaults are to use custom format. Which is compressed and uses pg_restore to recover.
## If format is set to plain, it is by default not compressed and psql is used to recover.
galaxy_docker_db_format: "custom" # other options 'plain' and 'tar'
galaxy_docker_db_compression_level: "{{(galaxy_docker_db_format=='custom') | ternary('6','0')}}"
galaxy_docker_db_restore_command: "{{(galaxy_docker_db_format=='plain') | ternary('psql','pg_restore -v')}}"
galaxy_docker_db_input_file_flag: "{(galaxy_docker_db_format=='plain') | ternary('-f','')}"

galaxy_docker_extracted_db_filename: "galaxy_database.{{ansible_date_time.iso8601}}.dump"
galaxy_docker_extracted_db_location: "{{galaxy_docker_docker_user_home}}/database_extract"

galaxy_docker_imported_db_location: "{{galaxy_docker_web_user_home}}/database/"
galaxy_docker_empty_database_script: "{{galaxy_docker_database_user_home}}/new_empty_db"

galaxy_docker_backup_location: "{{galaxy_docker_docker_user_home}}/backups"

# defaults for installtools
galaxy_docker_tool_dir: "/tmp/galaxy_tool_lists"

# defaults for installgenomes
galaxy_docker_dbkeys_dir: "/tmp/galaxy_dkeys_lists"
galaxy_docker_genome_copy_links: yes
galaxy_docker_genomes_dest: "{{docker_export_location}}/genomes"

# Ephemeris can be installed from git if extra functionality is needed which is not in the pypi package yet.
galaxy_docker_ephemeris_repo: "https://github.com/galaxyproject/ephemeris.git"
galaxy_docker_ephemeris_branch: "master"
galaxy_docker_ephemeris_dir: "{{galaxy_docker_docker_user_home}}/ephemeris"
ephemeris_from_git: False

#defaults for upgrade
galaxy_docker_test_upgrade: False
overwrite_config_files: False #Overwrites old config files with new distribution_config files


galaxy_docker_run_privileged: True
# Run
galaxy_docker_prepare_docker: False
galaxy_docker_prerequisites: False
galaxy_docker_template_galaxy_settings: False
galaxy_docker_upgrade: False
galaxy_docker_provision: False
galaxy_docker_run: False
galaxy_docker_add_users: False
galaxy_docker_add_user_ssh_keys: False
galaxy_docker_install_packages: False
galaxy_docker_create_export_folder: False
galaxy_docker_backup: False
galaxy_docker_cluster: False
galaxy_docker_transfer_genomes: False
galaxy_docker_change_uids: False
galaxy_docker_delete_system_files: False
galaxy_docker_delete_cron_jobs: False
galaxy_docker_delete: False
installdocker: False
importdb: False
upgrade: False
galaxywelcome: False
addldap: False
nginxsettings: False
ansible_role_nginx: False
galaxyfirewall: False
rundockergalaxy: False
cronbackupdb: False
installtools: False
extractdb: False
deletegalaxy: False
installgenomes: False
setupsge: False
customimage: False
