- include: installephemeris.yml

- include: container_running_check.yml

- include: installtools.yml
  when: galaxy_docker_provision_tools

- name: register whether the docker provision container is running
  command: "docker ps -q -f name={{galaxy_docker_provision_container_name}}$"
  register: provision_container_running
  tags:
  - skip_ansible_lint # https://github.com/willthames/ansible-lint/pull/292

- include: installgenomes.yml
  when: galaxy_docker_provision_genomes

- name: register whether the docker provision container is running
  command: "docker ps -q -f name={{galaxy_docker_provision_container_name}}$"
  register: provision_container_running
  tags:
  - skip_ansible_lint # https://github.com/willthames/ansible-lint/pull/292

- name: Remove the docker provision container
  docker_container:
    name: "{{galaxy_docker_provision_container_name}}"
    state: absent
  when:
    - provision_container_running.stdout !=''
