- include_tasks: installephemeris.yml

- include_tasks: container_running_check.yml

- include_tasks: installtools.yml
  when: galaxy_docker_provision_tools

- name: register whether the docker provision container is running
  command: "docker ps -q -f name={{galaxy_docker_provision_container_name}}$"
  register: provision_container_running

- include_tasks: installgenomes.yml
  when: galaxy_docker_provision_genomes

- name: register whether the docker provision container is running
  command: "docker ps -q -f name={{galaxy_docker_provision_container_name}}$"
  register: provision_container_running

- name: Remove the docker provision container
  docker_container:
    name: "{{galaxy_docker_provision_container_name}}"
    state: absent
  when:
    - provision_container_running.stdout !=''
