- include: importdb.yml
  when: importdb

- name: register whether the container is running
  command: "docker inspect -f {{inspect}} {{docker_container_name}}"
  vars:
    inspect: !unsafe '{{.State.Running}}'
  register: docker_running
  when: ( installtools or installgenomes )

- name: Show docker inspection results
  debug:
    var: docker_running
    verbosity: 1
  when: docker_running is defined

- include: start_provision_container.yml
  when:
    - docker_running is defined
    - not docker_running.stdout | bool

- name: Set provision key when starting provision container
  set_fact:
    galaxy_admin_api_key: "{{galaxy_docker_provision_key}}"
  when:
    - docker_running is defined
    - not docker_running.stdout | bool

- name: Use public web port when running production container
  set_fact:
    galaxy_docker_provision_port: "{{galaxy_web_port}}"
  when:
    - docker_running is defined
    - docker_running.stdout | bool

- include: installephemeris.yml
  when: ( installtools or installgenomes )

- name: Check if galaxy has started
  command: echo this always reports as changed
  notify: check if galaxy has started
  when: ( installtools or installgenomes )

- meta: flush_handlers

- include: installtools.yml
  when: installtools

- include: installgenomes.yml
  when: installgenomes
