- include: importdb.yml
  when: importdb

- debug:
    var: galaxy_docker_web_ssh_user

- include: transfer_genomes.yml
  when: installgenomes
  become: "{{galaxy_docker_become}}"
  become_user: "{{galaxy_docker_web_user}}"
  vars:
    ansible_ssh_user: "{{galaxy_docker_web_ssh_user}}"
    ansible_ssh_private_key_file: "{{galaxy_docker_web_user_private_key}}"

- include: installephemeris.yml
  when: ( installtools or installgenomes )

- include: container_running_check.yml

- include: installtools.yml
  when: installtools

- include: installgenomes.yml
  when: installgenomes
