
---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

- include: importdb.yml
  when: importdb

- include: transfer_genomes.yml
  when: galaxy_docker_transfer_genomes
  become: "{{galaxy_docker_become}}"
  become_user: "{{galaxy_docker_web_user}}"
  vars:
    ansible_ssh_user: "{{galaxy_docker_web_ssh_user}}"
    ansible_ssh_private_key_file: "{{galaxy_docker_web_user_private_key}}"

- include: installephemeris.yml
  when: ( installtools or installgenomes )

- include: container_running_check.yml

- include: installtools.yml
  when: installtools

- include: installgenomes.yml
  when: installgenomes

- name: register whether the docker provision container is running
  command: "docker inspect -f {{inspect}} {{docker_provision_container_name}}"
  vars:
    inspect: !unsafe '{{.State.Running}}'
  register: provision_container_running
  when: ( installtools or installgenomes )
  ignore_errors: yes # If the container does not exist this will run.

- name: Remove the docker provision container
  docker_container:
    name: "{{docker_provision_container_name}}"
    state: absent
  when: provision_container_running.stdout | bool
