---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

# this task installs ephemeris. It is used for installing tools and genomes.

- name: Create directory for ansible_generated vars
  file:
    path: "{{galaxy_docker_ansible_generated_vars_dir}}"
    state: directory
  become: no
  delegate_to: 127.0.0.1

- name: Create file with volume settings
  template:
    dest: "{{galaxy_docker_ansible_generated_vars_dir}}/docker_volumes_provision.yml"
    src: "docker_volumes_provision.yml.j2"
    force: yes
  become: no
  delegate_to: 127.0.0.1
  vars:
    ansible_ssh_pipelining: False
    
- name: Include port and volume settings
  include_vars: "{{galaxy_docker_ansible_generated_vars_dir}}/docker_volumes_provision.yml"

- name: Show volumes
  debug:
    var: docker_mounted_volumes
    verbosity: 1

- name: Update docker environment file
  template:
    src: docker_environment_provision.j2
    dest: "{{galaxy_docker_environment_file_location}}"
    mode: 0600

- name: Start the docker provision container
  docker_container:
    env_file: "{{galaxy_docker_environment_file_location}}"
    volumes: "{{docker_mounted_volumes}}"
    image: "{{galaxy_docker_docker_image}}"
    name: "{{galaxy_docker_provision_container_name}}"
    hostname: "{{galaxy_docker_container_hostname}}"
    published_ports: "127.0.0.1:{{galaxy_docker_provision_port}}:80"
    state: started
    restart: yes
  notify: check if provision galaxy has started

- name: remove docker environment file
  file:
    state: absent
    path: "{{galaxy_docker_environment_file_location}}"
