- name: Set parameters for deleting the test upgrade container
  set_fact:
    "{{item.key}}" : "{{item.value}}"
  with_dict: "{{test_upgrade}}"
  when: delete_test_upgrade

- name: Remove docker container
  docker_container:
    name: "{{docker_container_name}}"
    state: absent

- name: Remove docker export volumes
  file: 
    path: "{{docker_export_location}}"
    state: absent
  when: delete_files

- name: remove firewall port exception
  ufw:
    name: "{{ufw_profile}}"
    delete: yes
    state: reloaded

- name: remove firewall profile
  file:
    path: "/etc/ufw/applications.d/{{ufw_profile}}"
    state: absent
