---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

- name: Create user to run docker image
  user:
    createhome: yes
    name: "{{docker_user}}"
    groups: "{{user_groups}}"

- name: Update docker environment file
  template:
    src: docker_environment_dict.j2
    dest: "{{docker_environment_file_location}}"
    group: "{{docker_user}}"
    owner: "{{docker_user}}"
    mode: 0600

- name: Set docker published web port
  set_fact:
    docker_published_web_port: "127.0.0.1:{{galaxy_web_port}}:80"
  when:
    - galaxy_web_port is defined
    - galaxy_web_port != ''

- name: set docker published ftp port
  set_fact:
    docker_published_ftp_port: "127.0.0.1:{{galaxy_ftp_port}}:8021"
  when:
    - galaxy_ftp_port is defined
    - galaxy_ftp_port != ''

- name: set docker published sftp port
  set_fact:
    docker_published_sftp_port: "127.0.0.1:{{galaxy_sftp_port}}:8021"
  when:
    - galaxy_sftp_port is defined
    - galaxy_sftp_port != ''

- name: Create list of docker published ports
  set_fact:
    docker_published_ports: "{{docker_published_ports + item}}"
  with_items:
    - "{{docker_published_web_port | default('[]')}}"
    - "{{docker_published_ftp_port | default('[]')}}"
    - "{{docker_published_sftp_port | default('[]')}}"

- name: Show docker published ports
  debug:
    var: docker_published_ports
    verbosity: 0

- name: Restart the docker container
  docker_container:
    env_file: "{{docker_environment_file_location}}"
    volumes: "{{docker_export_location}}:/export/"
    image: "{{docker_image}}"
    name: "{{docker_container_name}}"
    published_ports: "{{docker_published_ports}}"
    state: started
    restart: yes
  become_user: "{{docker_user}}"
  become: yes
  notify: check if galaxy has started

- name: remove docker environment file
  file:
    state: absent
    path: "{{docker_environment_file_location}}"

- meta: flush_handlers
