# The docker container is only restarted after a change in the configuration.o

- name: Create user to run docker image
  user:
    createhome: yes
    name: "{{docker_user}}"
    groups: "{{user_groups}}"

- name: Update docker environment file
  template:
    src: docker_environment_dict.j2
    dest: "{{docker_environment_file_location}}"
    group: "{{docker_user}}"
    owner: "{{docker_user}}"
    mode: 0755

- name: Restart the docker container
  docker_container:
    env_file: "{{docker_environment_file_location}}"
    volumes: "{{docker_export_location}}:/export/"
    image: "{{docker_image}}"
    name: "{{docker_container_name}}"
    published_ports: "{{docker_published_ports}}"
    state: started
    restart: yes
  become_user: "{{docker_user}}"
  become: yes
  notify: check if galaxy has started

- meta: flush_handlers
