
---
# defaults file for cronbackupdb

container_postgres_user: 1550
container_database_name: galaxy
db_export_location: postgresql
cronbackupdb_log_timestamp: "TZ='UTC' date +'%Z %F %T >'"
backup_user: galaxy_backup
backup_ssh_key_file: ".ssh/id_rsa"
default_rsync_settings:
  delete: True
  compression_level: 0
  cron:
    special_time: "hourly"
    
backup_rsync_settings: {}
