---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

# this task installs ephemeris. It is used for installing tools and genomes.

- name: Install required ephemeris package
  pip:
    name: "{{ galaxy_docker_ephemeris_package }}"
    state: present
    version: "{{ galaxy_docker_ephemeris_version }}"
  when: not ephemeris_from_git

- name: install git
  package:
    name: git
    state: present
  when: ephemeris_from_git

- name: Clean ephemeris git folder
  file:
    path: "{{galaxy_docker_ephemeris_dir}}"
    state: absent
  when: ephemeris_from_git

- name: Install ephemeris repo
  git:
    repo: "{{galaxy_docker_ephemeris_repo}}"
    dest: "{{galaxy_docker_ephemeris_dir}}"
    version: "{{galaxy_docker_ephemeris_branch}}"
  when: ephemeris_from_git

- name: Install ephemeris requirements
  pip:
    requirements: "{{galaxy_docker_ephemeris_dir}}/requirements.txt"
    state: present
  when: ephemeris_from_git

- name: Install ephemeris from git repo
  command: "python setup.py install"
  args:
    chdir: "{{galaxy_docker_ephemeris_dir}}"
  when: ephemeris_from_git
