- name: Overwrite old config files?
  set_fact:
    no_overwrite: ""
  when: galaxy_docker_upgrade_overwrite_config_files

- name: Add new config files
  command: "rsync -p -r {{no_overwrite | default('--ignore-existing')}} {{src}} {{dest}}"
  vars:
    src: "{{galaxy_docker_export_location}}/.distribution_config/"
    dest: "{{galaxy_docker_export_location}}/galaxy-central/config"
  tags:
    - skip_ansible_lint # Synchronize module does not support copying on the same host.
