- include: ../prerequisites/nginxsettings.yml
  when: nginxsettings

- name: Setting new docker container for the test upgrade.
  set_fact:
    docker_container_name: "{{test_upgrade_settings.docker_container_name}}"
  when: test_upgrade

- include: upgrade.yml
  when: upgrade
