- name: Setting new docker container for the test upgrade.
  set_fact:
    galaxy_docker_container_name: "{{galaxy_docker_upgrade_test_settings.galaxy_docker_container_name}}"
  when: galaxy_docker_test_upgrade

- import_tasks: upgrade.yml
  when: galaxy_docker_upgrade or galaxy_docker_test_upgrade
