---
# vars file for installdocker
installdocker_prerequisites:
  - linux-image-extra-virtual
  - "linux-image-extra-{{ansible_kernel}}"

installdocker_python_packages:
  - python-pip
  - python-setuptools
installdocker_pip_packages:
  - docker-py
installdocker_gpg_key: "https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg"
installdocker_apt_repository: "deb https://download.docker.com/linux/{{ansible_distribution | lower}} {{ansible_distribution_release}} stable"
installdocker_packages:
  - docker-ce
