- name: check if galaxy has started
  uri:
    url: "http://localhost:{{galaxy_web_port}}"
    return_content: yes
  register: result
  until: '"{{galaxy_brand}}" in result.content'
  retries: 20 
  delay: 10
